config/routes.rb
Rails.application.routes.draw do

  # ActiveAdmin has everything
  ActiveAdmin.routes(self)

  # Login is only for admin features
  devise_for :users
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
  end

  # Normal users can see photos, see the contact page, and see the about page
  # Admin users can also create, update and delete photos and contact/about
  # page info
  root 'photos#index'
  resources :photos, except: [:show]

  get 'pages/about' => 'pages#about'
  get 'pages/contact' => 'pages#contact'
  namespace :pages do
    resources :about_sections
    resources :contact_sections
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed">
  <div class="container">

    <!-- Logo and mobile/tablet dropdown menu -->
    <div class="navbar-top">
      <div class="navbar-logo">
        <h1><%= "Natalie Lunt Photography" %></h1>
      </div>

      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-dropdown-mobile dropdown hidden-md hidden-lg">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About",pages_about_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
          <% if admin_user? %>
            <li><%= link_to'Add Photo', new_photo_path %></li>
            <li><%= link_to 'Admin Area', admin_dashboard_path %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <!-- Link buttons & admin link buttons -->
    <div class="navbar-links hidden-xs hidden-sm">
      <div class="links-left">
        <ul class="list-inline">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", pages_about_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
        </ul>
      </div>

      <% if admin_user? %>
        <div class="links-right">
          <ul class="list-inline btn-admin">
            <li><%= link_to'Add Photo', new_photo_path, class: 'btn btn-default btn-admin' %></li>
            <li><%= link_to 'Admin Area', admin_dashboard_path, class: 'btn btn-default' %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, class: 'btn btn-default', method: :delete %></li>
          </ul>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_photo_form.html.erb
<%= simple_form_for @photo do |f| %>
  <%= f.input :caption_title %>
  <%= f.input :caption_description %>
<!--   <%= f.input :image_location, label: "Image", as: :file, :hint => image_tag(f.object.image_location.url, width: 100) %> -->
  <%= f.input :image_location, label: "Image", required: true %>
  <%= f.input :image_location_cache, as: :hidden %>
  <%= f.association :categories, collection: Category.all.order(:name) %>
  <%= f.button :submit %>
<% end %>