config/routes.rb
Rails.application.routes.draw do

  # ActiveAdmin has everything
  ActiveAdmin.routes(self)

  # Login is only for admin features
  devise_for :users
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
  end

  # Normal users can see photos, see the contact page, and see the about page
  # Admin users can also create, update and delete photos and contact/about
  # page info
  root 'photos#index'
  resources :photos, except: [:show]

  get 'pages/about' => 'pages#about'
  get 'pages/contact' => 'pages#contact'
  namespace :pages do
    resources :about_sections
    resources :contact_sections
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
# == Constants ============================================================

# == Attributes ===========================================================

# == Extensions ===========================================================
  mount_uploader :image_location, ImageUploader
  acts_as_list top_of_list: 0
# == Relationships ========================================================
  has_many :category_entries, dependent: :destroy
  has_many :categories, through: :category_entries
# == Validations ==========================================================
  validate  :has_image
  validates :categories, presence: true
  validates :caption_title, length: { maximum: 60 }
  validates :caption_description, length: { maximum: 300 }
# == Scopes ===============================================================

# == Callbacks ============================================================
  after_destroy :delete_from_cloudinary
# == Class Methods ========================================================

# == Instance Methods =====================================================
  # used to add relevant css classes to each photo
  def categories_string
    self.categories.pluck(:name).sort.join(" ").downcase
  end

  def has_image
    if self.image_location.blank? && self.remote_image_location_url.blank?
      errors.add(:image_location, "must be provided")
    end
  end

  private
  def delete_from_cloudinary
    public_id = self.image_location.file.public_id
    Cloudinary::Uploader.destroy(public_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #normal user can only see photos. adding, editing and destroying photos
  #is done in admin view
  before_action :confirm_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_photo, only: [:edit, :update, :destroy]


  def index
    @photos = Photo.all
    @categories = Category.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @photo.update(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_path
  end


  private
  def find_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:caption_title, :caption_description,
                                  :image_location, :image_location_cache,
                                  :remote_image_location_url,
                                  :category_ids => [])
  end

  def confirm_admin
    redirect_to photos_path unless admin_user?
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<%= render 'shared/photo_form' %>

app/views/photos/index.html.erb
<div class="container">
  <div class="tabs-wrapping tabs filter-tabs">
    <a class="tab tab-active btn btn-default btn-sm" data-filter="*">All Photos</a>
    <% @categories.each do |category| %>
      <a class="tab btn btn-default btn-sm" data-filter=".<%= category.name.downcase %>"><%= category.name.titlecase %></a>
    <% end %>
  </div>

  <div id="masonry-grid" class="gallery padded">

    <div class="grid-sizer"></div>
    <% @photos.each do |photo| %>
      <!-- categories_string method is in photo model -->
      <div class="grid-item <%= photo.categories_string %>" data-category="<%= photo.categories_string %>">
        <div class="card-photo">

          <%= image_tag(photo.image_location, alt: photo.image_alt, class: "photo", width: 300, crop: :scale)%>

          <% if admin_user? %>
            <div class="card-photo-top-right">
              <%= link_to new_photo_path(photo), class: "btn-admin btn-transparent btn btn-xs btn-default" do %>
                <i class="fa fa-edit" aria-hidden="true"></i>
              <% end %>

              <%= link_to photo_path(photo), method: :delete, class: "btn-admin btn-transparent btn btn-xs btn-default" do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            </div>
          <% end %>

          <% unless photo.caption_title.blank?  && photo.caption_description.blank? %>
            <div class="card-photo-bottom hidden photo-caption">
              <h5><%= photo.caption_title %></h5>
              <p><%= photo.caption_description %></p>
            </div>
          <% end %>

        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/photos/new.html.erb
<%= render 'shared/photo_form' %>